# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ca627caf66aa93f59561e017f65ec9c86aa6016c06517069c20c35a40ac664c1564677dac99234974fbd80bdbfa8aea7b343a934f6800143918ea09e366be37

test:
  secret_key_base: 20ac93f6e6f955165a6f262cb28e1d088f9fdf6761e4847ec0bfa69af208131d8906780ca423e8c0ca3418ad810130c408be961845a8a543335b492b1ca2539c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
